name = "MyPackage"
uuid = "98594852-21cd-4122-adaf-d7d5a474cc4a"
authors = ["Stamatis Vretinaris"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
